#!/usr/bin/env python3
"""
Interactive API Setup Script

Guides you through setting up API credentials for Linear agent tasks.

Usage:
    python scripts/setup_apis.py
"""

import os
import sys
from pathlib import Path

def print_section(title: str):
    """Print a section header."""
    print()
    print("=" * 60)
    print(title)
    print("=" * 60)
    print()

def get_input(prompt: str, default: str = None, required: bool = True) -> str:
    """Get user input with optional default."""
    if default:
        full_prompt = f"{prompt} [{default}]: "
    else:
        full_prompt = f"{prompt}: "
    
    while True:
        value = input(full_prompt).strip()
        if value:
            return value
        elif default:
            return default
        elif not required:
            return ""
        else:
            print("  This field is required. Please enter a value.")

def setup_linear():
    """Setup Linear API configuration."""
    print_section("Linear API Setup")
    
    print("To get your Linear API key:")
    print("1. Go to Linear → Settings → API")
    print("2. Click 'Create Personal API Key'")
    print("3. Copy the API key (starts with 'lin_api_')")
    print()
    
    api_key = get_input("Enter your Linear API key", required=True)
    team_key = get_input("Enter your Linear team key (e.g., 'TRA')", default="TRA", required=False)
    
    return {
        'LINEAR_API_KEY': api_key,
        'LINEAR_TEAM_KEY': team_key
    }

def setup_google():
    """Setup Google APIs configuration."""
    print_section("Google APIs Setup")
    
    print("To set up Google APIs:")
    print("1. Go to https://console.cloud.google.com/")
    print("2. Create a project or select existing")
    print("3. Enable APIs: Google Docs API, Google Sheets API, Google Drive API")
    print("4. Create credentials (Service Account recommended)")
    print("5. Download the JSON credentials file")
    print()
    print("For Service Account:")
    print("- Create Service Account → Download JSON key")
    print("- Share target Google Drive folders with service account email")
    print()
    print("For OAuth:")
    print("- Create OAuth 2.0 credentials → Download JSON")
    print("- Complete OAuth flow on first use")
    print()
    
    creds_path = get_input("Enter path to Google credentials JSON file", required=True)
    
    # Check if file exists
    if not os.path.exists(creds_path):
        print(f"⚠️  Warning: File not found: {creds_path}")
        confirm = input("Continue anyway? (y/n): ").strip().lower()
        if confirm != 'y':
            return None
    
    folder_id = get_input("Enter Google Drive folder ID (optional, press Enter to skip)", required=False)
    
    return {
        'GOOGLE_CREDENTIALS_PATH': creds_path,
        'GOOGLE_DRIVE_FOLDER_ID': folder_id
    }

def setup_activecampaign():
    """Setup ActiveCampaign API configuration."""
    print_section("ActiveCampaign API Setup")
    
    print("To get your ActiveCampaign API credentials:")
    print("1. Go to ActiveCampaign → Settings → Developer")
    print("2. Find your API URL (format: https://{account}.api-us1.com)")
    print("3. Find your API Key")
    print()
    print("Note: Use the Trade Ideas ActiveCampaign account")
    print()
    
    api_url = get_input("Enter ActiveCampaign API URL", required=True)
    api_key = get_input("Enter ActiveCampaign API Key", required=True)
    
    # Validate URL format
    if not api_url.startswith('https://') or '.api-' not in api_url:
        print("⚠️  Warning: API URL format looks incorrect. Should be: https://{account}.api-us1.com")
        confirm = input("Continue anyway? (y/n): ").strip().lower()
        if confirm != 'y':
            return None
    
    return {
        'ACTIVE_CAMPAIGN_API_URL': api_url,
        'ACTIVE_CAMPAIGN_API_KEY': api_key
    }

def write_env_file(config: dict, env_path: Path):
    """Write configuration to .env file."""
    lines = []
    lines.append("# Linear Agent Tasks - Environment Variables")
    lines.append("# Generated by setup_apis.py")
    lines.append("")
    
    # Group by service
    linear_vars = {k: v for k, v in config.items() if k.startswith('LINEAR')}
    google_vars = {k: v for k, v in config.items() if k.startswith('GOOGLE')}
    ac_vars = {k: v for k, v in config.items() if k.startswith('ACTIVE_CAMPAIGN')}
    
    if linear_vars:
        lines.append("# Linear API Configuration")
        for key, value in linear_vars.items():
            lines.append(f"{key}={value}")
        lines.append("")
    
    if google_vars:
        lines.append("# Google APIs Configuration")
        for key, value in google_vars.items():
            lines.append(f"{key}={value}")
        lines.append("")
    
    if ac_vars:
        lines.append("# ActiveCampaign API Configuration")
        for key, value in ac_vars.items():
            lines.append(f"{key}={value}")
        lines.append("")
    
    env_path.write_text('\n'.join(lines))
    print(f"✅ Configuration saved to {env_path}")

def main():
    """Main setup function."""
    print("=" * 60)
    print("Linear Agent Tasks - API Setup")
    print("=" * 60)
    print()
    print("This script will guide you through setting up API credentials.")
    print("You can skip any section by pressing Ctrl+C and running again later.")
    print()
    
    workspace_root = Path(__file__).parent.parent
    env_path = workspace_root / '.env'
    env_template = workspace_root / '.env.template'
    
    # Check if .env already exists
    if env_path.exists():
        print(f"⚠️  .env file already exists at {env_path}")
        overwrite = input("Overwrite? (y/n): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return 1
    
    config = {}
    
    try:
        # Linear API
        print("\n📋 Step 1: Linear API")
        linear_config = setup_linear()
        if linear_config:
            config.update(linear_config)
        
        # Google APIs
        print("\n📋 Step 2: Google APIs")
        google_config = setup_google()
        if google_config:
            config.update(google_config)
        
        # ActiveCampaign API
        print("\n📋 Step 3: ActiveCampaign API")
        ac_config = setup_activecampaign()
        if ac_config:
            config.update(ac_config)
        
        # Write .env file
        if config:
            write_env_file(config, env_path)
            print()
            print("=" * 60)
            print("✅ Setup Complete!")
            print("=" * 60)
            print()
            print("Next steps:")
            print("1. Verify your configuration:")
            print("   python scripts/validate_apis.py")
            print()
            print("2. Start executing tasks:")
            print("   python scripts/execute_tasks.py --phase quick-wins")
            print()
            return 0
        else:
            print("\n❌ No configuration was saved.")
            return 1
            
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup interrupted.")
        if config:
            save = input("Save partial configuration? (y/n): ").strip().lower()
            if save == 'y':
                write_env_file(config, env_path)
                print(f"✅ Partial configuration saved to {env_path}")
        return 1
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
        return 1

if __name__ == '__main__':
    sys.exit(main())
